name: easy_gpt_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  chat_gpt_sdk:
    git:
      url: https://github.com/redevRx/Flutter-ChatGPT
  freezed_annotation: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^7.0.1
  progress_indicators: ^1.0.0
  url_launcher: ^6.1.7
  bloc_test: ^9.1.0
  dio: ^4.0.6
  intl: ^0.17.0
  google_mobile_ads: ^2.3.0
  injectable: ^2.1.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.1
  freezed: ^2.1.1
  mocktail: ^0.3.0
  injectable_generator: ^2.1.3

flutter:
  generate: true
  uses-material-design: true
  assets: 
    - assets/images/

  