name: easy_gpt_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.1.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  chat_gpt_sdk:
    git:
      url: https://github.com/kamiljasinski191/Flutter-ChatGPT
  freezed_annotation: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^7.0.1
  progress_indicators: ^1.0.0
  url_launcher: ^6.1.7
  bloc_test: ^9.1.0
  dio: ^4.0.6
  intl: ^0.17.0
  google_mobile_ads: ^2.3.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  firebase_core: ^2.9.0
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^6.5.5
  flutter_svg: ^2.0.5
  envied: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.1
  freezed: ^2.1.1
  mocktail: ^0.3.0
  injectable_generator: ^2.1.3
  flutter_launcher_icons: ^0.11.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  envied_generator: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets: 
    - assets/images/

  